#!/usr/bin/python3

import os
import subprocess
import sys

if os.getuid() != 0:
    print("mokutil-gui needs to be run as root.")
    sys.exit(1)

subprocess.Popen("/usr/lib/mokutil-gui/mokutil-gui.py")
